
FROM postgis/postgis:16-3.4

RUN apt-get update && apt-get install -y \
    postgis \
    postgresql-contrib \
    && rm -rf /var/lib/apt/lists/*

COPY ./backend/init_scripts/ /docker-entrypoint-initdb.d/

ENV POSTGRES_USER=openlayers
ENV POSTGRES_PASSWORD=openlayerssplineviewer
ENV POSTGRES_DB=openlayers