FROM postgres:16

RUN apt-get update && apt-get install -y \
    build-essential autoconf automake libtool \
    bison flex libxml2-dev libgeos-dev libproj-dev \
    libgdal-dev libjson-c-dev postgresql-server-dev-16 \
    && rm -rf /var/lib/apt/lists/*

COPY ./postgis_source /tmp/postgis_source
WORKDIR /tmp/postgis_source
RUN ./autogen.sh && \
    ./configure --without-protobuf && \
    make -j$(nproc) && \
    make install

COPY ./init_scripts/ /docker-entrypoint-initdb.d/

ENV POSTGRES_USER=openlayers
ENV POSTGRES_PASSWORD=openlayerssplineviewer
ENV POSTGRES_DB=openlayers